### ISSUE TITLE
Cannot run "npm install" on projects that use this fork of react-native-msal without having yarn installed

### ISSUE THREAD

**Issue by tormodAase** [equinor/react-native-msal#12]
**Bug Description:**
If a project uses this fork as a dependency, npm install won't work unless you have yarn installed on your machine. 

**Steps To Reproduce:**
- Uninstall yarn (if it is installed on your computer)
- (not sure if needed) delete node_modules folder in the project you want to reproduce this in (e.g. [OM Inspection](https://github.com/equinor/mad-project-om-inspection))
- Run `npm install` in the above project

**Expected Behavior:**
Installation of packages should work just fine

**Environment Information:**
 - `react-native-msal` version: [f1069d3](https://github.com/equinor/react-native-msal/commit/f1069d3b8f6ca911f60af1ddce45c8512bc58714) (though I believe this will happen in any commit)
 - `react-native` version: any
 - Platform: iOS

**Additional Information:**
I believe this happens because we use this package directly from github, without building it first.

**Comment by tormodAase** [comment]
The bug was found by Henning.
@dansvend @HaakonSvane

**Comment by MAgungHKM** [comment]
From my findings, the root cause is `expo-module-scripts`. That package has `npx` bash file which supposed to detect wether you use `yarn exec` or `npx`, but the if condition appears to be incorrect, as we can see over at https://github.com/expo/expo/commit/d295e37d1e623ca8abe067ae7dbb2841bc81e96d.

So either update the `expo-modules-scripts` package or apply a `patch-package` to that specific bash file.
